using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Configuration;
using System.Xml;

namespace OfficeBatchProcess
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.34209
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------



    public sealed class BatchConfig
    {
        static BatchConfig()
        {
            Config = ((BatchConfigSection)(global::System.Configuration.ConfigurationManager.GetSection("BatchConfig")));
        }

        private BatchConfig()
        {
        }

        public static BatchConfigSection Config { get; private set; }
    }

    public sealed partial class BatchConfigSection : System.Configuration.ConfigurationSection
    {

        [System.Configuration.ConfigurationPropertyAttribute("ProcessParams")]
        [System.Configuration.ConfigurationCollectionAttribute(typeof(ProcessParamsElementCollection.ParamElement), AddItemName = "Param")]
        public ProcessParamsElementCollection ProcessParams
        {
            get
            {
                return ((ProcessParamsElementCollection)(this["ProcessParams"]));
            }
        }

        public sealed partial class ProcessParamsElementCollection : System.Configuration.ConfigurationElementCollection
        {

            public ParamElement this[int i]
            {
                get
                {
                    return ((ParamElement)(this.BaseGet(i)));
                }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new ParamElement("id" + this.Count.ToString());
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((ParamElement)(element)).Name;
            }

            public sealed partial class ParamElement : System.Configuration.ConfigurationElement
            {
                public string Name;

                public ParamElement(string Name = "")
                {
                    this.Name = Name;
                }

                [System.Configuration.ConfigurationPropertyAttribute("XLSName", IsRequired = true)]
                public string XLSName
                {
                    get
                    {
                        return ((string)(this["XLSName"]));
                    }
                    set
                    {
                        this["XLSName"] = value;
                    }
                }


                [System.Configuration.ConfigurationPropertyAttribute("ZipObjectPath", IsRequired = true)]
                public string ZipObjectPath
                {
                    get
                    {
                        return ((string)(this["ZipObjectPath"]));
                    }
                    set
                    {
                        this["ZipObjectPath"] = value;
                    }
                }

                [System.Configuration.ConfigurationPropertyAttribute("NodeXPath", IsRequired = true)]
                public string NodeXPath
                {
                    get
                    {
                        return ((string)(this["NodeXPath"]));
                    }
                    set
                    {
                        this["NodeXPath"] = value;
                    }
                }

                [System.Configuration.ConfigurationPropertyAttribute("NodeNamespace", IsRequired = true)]
                public string NodeNamespace
                {
                    get
                    {
                        return ((string)(this["NodeNamespace"]));
                    }
                    set
                    {
                        this["NodeNamespace"] = value;
                    }
                }

                [System.Configuration.ConfigurationPropertyAttribute("ReplaceAttributes")]
                [System.Configuration.ConfigurationCollectionAttribute(typeof(ReplaceAttributesElementCollection.ReplaceElement), AddItemName = "Replace")]
                public ReplaceAttributesElementCollection ReplaceAttributes
                {
                    get
                    {
                        return ((ReplaceAttributesElementCollection)(this["ReplaceAttributes"]));
                    }
                }


                public sealed partial class ReplaceAttributesElementCollection : System.Configuration.ConfigurationElementCollection
                {

                    public ReplaceElement this[int i]
                    {
                        get
                        {
                            return ((ReplaceElement)(this.BaseGet(i)));
                        }
                    }

                    protected override System.Configuration.ConfigurationElement CreateNewElement()
                    {
                        return new ReplaceElement("id" + Count.ToString());
                    }

                    protected override object GetElementKey(System.Configuration.ConfigurationElement element)
                    {
                        return ((ReplaceElement)(element)).Name;
                    }

                    public sealed partial class ReplaceElement : System.Configuration.ConfigurationElement
                    {
                        public string Name;

                        public ReplaceElement(string Name = "")
                        {
                            this.Name = Name;
                        }

                        [System.Configuration.ConfigurationPropertyAttribute("AttributeName", IsRequired = false)]
                        public string AttributeName
                        {
                            get
                            {
                                return ((string)(this["AttributeName"]));
                            }
                            set
                            {
                                this["AttributeName"] = value;
                            }
                        }

                        [System.Configuration.ConfigurationPropertyAttribute("ReplaceValue", IsRequired = true)]
                        public string ReplaceValue
                        {
                            get
                            {
                                return ((string)(this["ReplaceValue"]));
                            }
                            set
                            {
                                this["ReplaceValue"] = value;
                            }
                        }

                        [System.Configuration.ConfigurationPropertyAttribute("OriginalValue", IsRequired = true)]
                        public string OriginalValue
                        {
                            get
                            {
                                return ((string)(this["OriginalValue"]));
                            }
                            set
                            {
                                this["OriginalValue"] = value;
                            }
                        }

                        [System.Configuration.ConfigurationPropertyAttribute("AttributeNameForDashReplace", DefaultValue = "")]
                        public string AttributeNameForDashReplace
                        {
                            get
                            {
                                return ((string)(this["AttributeNameForDashReplace"]));
                            }
                            set
                            {
                                this["AttributeNameForDashReplace"] = value;
                            }
                        }

                        [System.Configuration.ConfigurationPropertyAttribute("DefaultValueForDashReplace", DefaultValue = "")]
                        public string DefaultValueForDashReplace
                        {
                            get
                            {
                                return ((string)(this["DefaultValueForDashReplace"]));
                            }
                            set
                            {
                                this["DefaultValueForDashReplace"] = value;
                            }
                        }
                        
                            
                    }
                }

                [System.Configuration.ConfigurationPropertyAttribute("DeduplicateElements")]
                [System.Configuration.ConfigurationCollectionAttribute(typeof(DeduplicateElementsElementCollection.DeduplicateElement), AddItemName = "Deduplicate")]
                public DeduplicateElementsElementCollection DeduplicateElements
                {
                    get
                    {
                        return ((DeduplicateElementsElementCollection)(this["DeduplicateElements"]));
                    }
                }

                public sealed partial class DeduplicateElementsElementCollection : System.Configuration.ConfigurationElementCollection
                {

                    public DeduplicateElement this[int i]
                    {
                        get
                        {
                            return ((DeduplicateElement)(this.BaseGet(i)));
                        }
                    }

                    protected override System.Configuration.ConfigurationElement CreateNewElement()
                    {
                        return new DeduplicateElement();
                    }

                    protected override object GetElementKey(System.Configuration.ConfigurationElement element)
                    {
                        return ((DeduplicateElement)(element)).XMLElement;
                    }

                    public sealed partial class DeduplicateElement : System.Configuration.ConfigurationElement
                    {

                        [System.Configuration.ConfigurationPropertyAttribute("XMLElement", IsRequired = false)]
                        public string XMLElement
                        {
                            get
                            {
                                return ((string)(this["XMLElement"]));
                            }
                            set
                            {
                                this["XMLElement"] = value;
                            }
                        }

                        [System.Configuration.ConfigurationPropertyAttribute("XMLKey", IsRequired = true)]
                        public string XMLKey
                        {
                            get
                            {
                                return ((string)(this["XMLKey"]));
                            }
                            set
                            {
                                this["XMLKey"] = value;
                            }
                        }

                        [System.Configuration.ConfigurationPropertyAttribute("Mode", DefaultValue = "Remove")]
                        public string Mode
                        {
                            get
                            {
                                return ((string)(this["Mode"]));
                            }
                            set
                            {
                                this["Mode"] = value;
                            }
                        }

                        [System.Configuration.ConfigurationPropertyAttribute("CascadeRemoves")]
                        [System.Configuration.ConfigurationCollectionAttribute(typeof(CascadeRemovesElementCollection.CascadeRemoveElement), AddItemName = "CascadeRemove")]
                        public CascadeRemovesElementCollection CascadeRemoves
                        {
                            get
                            {
                                return ((CascadeRemovesElementCollection)(this["CascadeRemoves"]));
                            }
                        }

                        public sealed partial class CascadeRemovesElementCollection : System.Configuration.ConfigurationElementCollection
                        {

                            public CascadeRemoveElement this[int i]
                            {
                                get
                                {
                                    return ((CascadeRemoveElement)(this.BaseGet(i)));
                                }
                            }

                            protected override System.Configuration.ConfigurationElement CreateNewElement()
                            {
                                return new CascadeRemoveElement();
                            }

                            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
                            {
                                return ((CascadeRemoveElement)(element)).Id;
                            }

                            public sealed partial class CascadeRemoveElement : System.Configuration.ConfigurationElement
                            {

                                [System.Configuration.ConfigurationPropertyAttribute("Id", IsRequired = true)]
                                public long Id
                                {
                                    get
                                    {
                                        return ((long)(this["Id"]));
                                    }
                                    set
                                    {
                                        this["Id"] = value;
                                    }
                                }

                                [System.Configuration.ConfigurationPropertyAttribute("CascadeFrom", IsRequired = true)]
                                public long CascadeFrom
                                {
                                    get
                                    {
                                        return ((long)(this["CascadeFrom"]));
                                    }
                                    set
                                    {
                                        this["CascadeFrom"] = value;
                                    }
                                }

                                [System.Configuration.ConfigurationPropertyAttribute("UpdateLinkedIndexElement", IsRequired = true)]
                                public string UpdateLinkedIndexElement
                                {
                                    get
                                    {
                                        return ((string)(this["UpdateLinkedIndexElement"]));
                                    }
                                    set
                                    {
                                        this["UpdateLinkedIndexElement"] = value;
                                    }
                                }

                                [System.Configuration.ConfigurationPropertyAttribute("UpdateLinkedIndexAttribute", IsRequired = true)]
                                public string UpdateLinkedIndexAttribute
                                {
                                    get
                                    {
                                        return ((string)(this["UpdateLinkedIndexAttribute"]));
                                    }
                                    set
                                    {
                                        this["UpdateLinkedIndexAttribute"] = value;
                                    }
                                }

                                [System.Configuration.ConfigurationPropertyAttribute("ParentAttributeNameForXPathDash", DefaultValue = "")]
                                public string ParentAttributeNameForXPathDash
                                {
                                    get
                                    {
                                        return ((string)(this["ParentAttributeNameForXPathDash"]));
                                    }
                                    set
                                    {
                                        this["ParentAttributeNameForXPathDash"] = value;
                                    }
                                }
                        
                            }
                        }
                    }
                }


                [System.Configuration.ConfigurationPropertyAttribute("ExtractContents")]
                [System.Configuration.ConfigurationCollectionAttribute(typeof(ExtractContentsElementCollection.Extract), AddItemName = "Extract")]
                public ExtractContentsElementCollection ExtractContents
                {
                    get
                    {
                        return ((ExtractContentsElementCollection)(this["ExtractContents"]));
                    }
                }


                public sealed partial class ExtractContentsElementCollection : System.Configuration.ConfigurationElementCollection
                {

                    public Extract this[int i]
                    {
                        get
                        {
                            return ((Extract)(this.BaseGet(i)));
                        }
                    }

                    protected override System.Configuration.ConfigurationElement CreateNewElement()
                    {
                        return new Extract("id" + Count.ToString());
                    }

                    protected override object GetElementKey(System.Configuration.ConfigurationElement element)
                    {
                        return ((Extract)(element)).Name;
                    }

                    public sealed partial class Extract : System.Configuration.ConfigurationElement
                    {
                        public string Name;

                        public Extract(string Name = "")
                        {
                            this.Name = Name;
                        }

                        [System.Configuration.ConfigurationPropertyAttribute("SliceByXPaths", IsRequired = false)]
                        public string SliceByXPaths
                        {
                            get
                            {
                                return ((string)(this["SliceByXPaths"]));
                            }
                            set
                            {
                                this["SliceByXPaths"] = value;
                            }
                        }



                        


                    }
                }
            }
        }
    }


}
